### PR TITLE
add graphql icon

### PR DESCRIPTION
**Pull request by kumarharsh**
I've added an icon for graphql. I've only added the `.svg` and changes in the `mapping.less` file to my PR. Do let me know if you need the generated files too.

image

### CODE REVIEW

**Comment by orta** [comment]
This is perfect, thanks @kumarharsh

**Comment by kumarharsh** [comment]
Oh! That's a pleasant surprise!

How many projects are you gonna maintain? 😋 On a serious note, are you going to be maintaining this henceforth? There's an open issue in VSCode: https://github.com/microsoft/vscode/issues/73178#issuecomment-509144536 regarding this repo's status.

**Comment by orta** [comment]
replied in there, thanks!

**Comment by kumarharsh** [comment]
Nice. I'd be willing to donate some time to this too, if you need it.

**Comment by orta** [comment]
Ace, I'm open - I don't have admin access to add more folks. If it gets to be more than 1 PR a day, then I'm happy to poke Jesses to get more folks in

**Pull request merged**
