### PR TITLE
Update platformio.svg

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by ivankravets** [comment]
Please update PlatformIO SVG. The current looks ugly. Thanks!

Screen Shot 2019-08-13 at 14 00 27

**Comment by orta** [comment]
👍 did you test this in vscode?

**Comment by ivankravets** [comment]
Sorry, didn't test. I tried to build `seti.woff` but `gulp icon` produces a lot of Node.JS errors. Maybe something is wrong with my dev/environment or Node.JS version.

In any case, I just followed this guide "You want to aim for a frame of 32x32 with the icon centered at and being about 18 x 18 big. ". See picture below with 32x32 icon:

Screen Shot 2019-08-14 at 11 55 00

**Comment by orta** [comment]
OK, 👍 then we'll see what it looks like next time the vscode team update

**Comment by ivankravets** [comment]
Thanks! Do you know how often they do these updates?

**Comment by orta** [comment]
They release vscode monthly, but I'm unsure if they schedule updating the icons - I did it last time but there'd need to be quite a few more updates before I'll send a new version over. You're welcome to give it a shot yourself though.

**Pull request merged**
