### PR TITLE
Add support for golang

### PR DESCRIPTION
**Pull request by swhite24**
Add blue golang gopher icon.

### CODE REVIEW

**Comment by jesseweed** [comment]
Look good! I'll try and get this in this weekend. Thanks!

**Comment by jesseweed** [comment]
Hey sorry @swhite24, looks like the also overrides the Typescript icon (.ts) with the Go icon. Can you re-update the icon font and send again? Thanks!

**Comment by swhite24** [comment]
@jesseweed Sorry for that.  Should be good now.

**Comment by andreis** [comment]
Any updates on this? Thanks

**Comment by andreis** [comment]
Awesome, thank you @jesseweed !

**Pull request merged**
