### PR TITLE
assign icons for go.mod and go.sum files

### PR DESCRIPTION
**Pull request by hyangah**
.mod file is recognized as an xml file in vscode.
We were advised to specify the icon for go.mod files.
Since go.sum is paired with go.mod, add it as well.

Reusing the icon for go files, but with different colors
to visually distinguish them from regular go files.

Applied gulp svg; gulp icon.

Update microsoft/vscode#98586

image

### CODE REVIEW

**Comment by hyangah** [comment]
switched the color mapping (so go.mod is yellow and go.sum is light-grey).

**Comment by orta** [comment]
Hi, I'm good with merging this change, but because it includes all the derived files like `styles/_fonts/seti/seti.eot`it's got merge conflicts! Any chance I can get you to either ship without those files or update to master?

**Comment by orta** [comment]
Poke

**Comment by orta** [comment]
Alright, I'm open to someone re-submitting this PR 👍🏻

**Pull request closed without merging**
