### PR TITLE
Updated Gradle file icon to newest Gradle logo version

### PR DESCRIPTION
**Pull request by azilnik**
The `.gradle` file icon uses an old Gradle logo. This pull request updates this icon to use the newest logo.

### CODE REVIEW

**Comment by orta** [comment]
Looking at the sizes of the new SVG, I think you probably want to tweak it so the frame stays at 43 and that the elephant takes up more space in the frame

Screen Shot 2020-07-16 at 10 11 23 PM

And did you mean to include the cuda change?
Screen Shot 2020-07-16 at 10 13 08 PM

**Comment by azilnik** [comment]
Good call, will do @orta

**Comment by azilnik** [comment]
@orta I have managed to update the icon to a newer version, but every time I run `gulp svg` it seems to modify the Cuda icon as well, as mentioned in https://github.com/jesseweed/seti-ui/pull/574#issuecomment-659790656. So strange! Any idea why?

**Comment by azilnik** [comment]
Dupe of #575

**Pull request closed without merging**
