### PR TITLE
update Java icon

### PR DESCRIPTION
**Pull request by Eskibear**
fix https://github.com/jesseweed/seti-ui/issues/538

### CODE REVIEW

**Comment by orta** [comment]
Cool, this looks good to me!

**Comment by Eskibear** [comment]
I find vscode's latest release is still using the old icon. Just curious about when would vscode eventually adopt this change? Thanks.

**Comment by orta** [comment]
They update ad-hoc, I think you can probably go update for them though (it'll be documented in their repo somewhere)

**Comment by Eskibear** [comment]
Thank you for the information, it's documented [here](https://github.com/microsoft/vscode/blob/main/extensions/theme-seti/CONTRIBUTING.md#updating-icons).

**Comment by GavinRay97** [comment]
Oh wow, thank you so much for this!
Have wanted this forever

**Pull request merged**
