### PR TITLE
Added Cake Build Icon

### PR DESCRIPTION
**Pull request by gep13**
Added Icon for [Cake Build](http://cakebuild.net/) after reading about this Icon Theme Set on this blog post: http://code.visualstudio.com/blogs/2016/09/08/icon-themes

Please let me know if there is anything I need to correct.  Thanks!

### CODE REVIEW

**Comment by gep13** [comment]
@jesseweed just wondering if there is anything else I need to do to this in order to get it pulled in.  Are you in a position to review the PR?  Thanks!

**Comment by gep13** [comment]
@jesseweed thank you for merging this! Are you planning a release, or should this be immediately available?

**Comment by jesseweed** [comment]
@gep13 I just pushed a 1.4 release which includes all the recent pull requests.

**Comment by gep13** [comment]
Nice one!

**Pull request merged**
